### ISSUE TITLE
Can't specify custom config file

### ISSUE THREAD

**Issue by vtlim** [JustinBeckwith/linkinator-action#136]
When I set **config** in my GitHub actions configuration, Linkinator displays a warning and doesn't seem to pick up the properties in my Linkinator config file.

Snippet of GH yaml file:
```
    - name: Linkinator
      uses: JustinBeckwith/linkinator-action@v1.0.9
      with:
        paths: docs/
        config: linkinator.config.json
```

Contents of `linkinator.config.json`
```
{
  "recurse": true,
  "concurrency": 5,
  "timeout": 20000
}
```

The error in GitHub Actions. It seems to recognize the file, but uses the default `recurse` and `concurrency` anyway.
![image](https://user-images.githubusercontent.com/7747997/179326936-cd51331c-2dac-4012-860a-98501536c4d2.png)
