### ISSUE TITLE
Started getting HTTP 503 for working link

### ISSUE THREAD

**Issue by DavidAnson** [JustinBeckwith/linkinator-action#140]
https://thisdavej.com/build-an-amazing-markdown-editor-using-visual-studio-code-and-pandoc/

Reproduces over multiple runs. Link loads fine on its own in a browser. Possible throttling?

Example run: https://github.com/DavidAnson/vscode-markdownlint/runs/8114404271?check_suite_focus=true

**Comment by DavidAnson** [comment]
Debug run here: https://github.com/DavidAnson/vscode-markdownlint/runs/8117651040?check_suite_focus=true

Confirms they are on Cloudflare. I haven’t analyzed the byte buffer, but I think this came up before and the HTML included text saying they were throttling. It would maybe be nice to detect this scenario and report indeterminate instead of failing?

**Comment by DavidAnson** [comment]
Relevant discussion from Twitter: https://twitter.com/davidans/status/1528955012319105024?s=21&t=ORv_sfTYCCVv-IquAAocig

**Comment by JustinBeckwith** [comment]
I've investigated this issue. Here's what I found:

## The Problem
You experienced intermittent HTTP 503 errors from Cloudflare-protected sites (like thisdavej.com) that were likely due to rate limiting or throttling. The link would work in a browser but fail in CI.

## The Solution - Now Available!
The `retryErrors` option, which automatically retries 5xx errors (including 503), was **added in v2.0.0** (released October 2025).

At the time you reported this issue (August 2022), only the `retry` option existed, which only handled 429 responses with retry-after headers. There was no automatic retry for 503 errors.

## How to Fix
Use the `retryErrors` option in your workflow:

```yaml
- uses: JustinBeckwith/linkinator-action@v2
  with:
    paths: '**/*.md'
    retryErrors: true           # Retry 5xx errors including 503
    retryErrorsCount: 3         # Number of retry attempts (default: 3)
    retryErrorsJitter: 2000     # Max jitter in ms (default: 2000)
```

This will automatically retry 503 responses with exponential backoff and jitter, which should resolve intermittent Cloudflare throttling issues.

## Current Status
✅ The URL (https://thisdavej.com/build-an-amazing-markdown-editor-using-visual-studio-code-and-pandoc/) currently returns HTTP 200
✅ The `retryErrors` feature is available in v2.0.0

@DavidAnson If you're still experiencing this issue, please upgrade to v2 and enable `retryErrors`. Let me know if that resolves it!
